# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/DSL4/dsl4_demo_app/dsl4_demo_app.cache/wt [current_project]
set_property parent.project_path C:/DSL4/dsl4_demo_app/dsl4_demo_app.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/MouseTransmitter.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/MouseReceiver.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/MouseMasterSM.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/Downloads/generic_counter.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/VGA_Sig_Gen.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/Frame_Buffer.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/Downloads/TenHz_cnt.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/Downloads/IRTrasmitterSM.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/SevenSegmentDisplay.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/ALU.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/MouseTransceiver.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/new/VGA_Controller.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/IR/Switches.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/IR/Buttons.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/imports/IR/IR_Wrapper.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/Timer.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/SevSegDisBus.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/ROM.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/RAM.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/Processor.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/LedBus.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/MouseBus.v
  C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/sources_1/new/TOP.v
}
read_xdc C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/constrs_1/imports/new/Mouse_interface.xdc
set_property used_in_implementation false [get_files C:/DSL4/dsl4_demo_app/dsl4_demo_app.srcs/constrs_1/imports/new/Mouse_interface.xdc]

synth_design -top TOP -part xc7a35tcpg236-1
write_checkpoint -noxdef TOP.dcp
catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
